ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
autoInstallPeers: false

onlyBuiltDependencies:
  - esbuild
